### ISSUE TITLE
package.json : missing

### ISSUE THREAD

**Issue by yboujraf** [fancellu/neo4j-d3v4#1]
Dear @fancellu 

Do you have the package.json to setup correctly your project ?

Best Regards
Youssef

**Comment by fancellu** [comment]
Um,. there is no package.json

This isn't node.js, this is javascript

standalone.html is a canned demo

index.html talks to a neo4j db

**Comment by yboujraf** [comment]
Dear @fancellu 

I tried both examples : 
- standalone (OK)
- neo4jQuery (blank page)even if I have connected to my graphDB and I have tested successfully the getLinks(), getNodes().

Best Regards
Youssef

**Comment by fancellu** [comment]
I can't say. Best look at the console, see if there is anything
complaining.

**Comment by yboujraf** [comment]
Dear @fancellu 

My error is coming from this line : 

<script src="https://cdn.rawgit.com/neo4j/neo4j-javascript-driver/1.2/lib/browser/neo4j-web.min.js"></script>

```
Uncaught (in promise) Error: Unknown Bolt protocol version: 0
    n https://cdn.rawgit.com/neo4j/neo4j-javascript-driver/1.2/lib/browser/neo4j-web.min.js:17
    t https://cdn.rawgit.com/neo4j/neo4j-javascript-driver/1.2/lib/browser/neo4j-web.min.js:17
    onmessage https://cdn.rawgit.com/neo4j/neo4j-javascript-driver/1.2/lib/browser/neo4j-web.min.js:18
    onmessage https://cdn.rawgit.com/neo4j/neo4j-javascript-driver/1.2/lib/browser/neo4j-web.min.js:18
[neo4j-web.min.js:17:6334](https://cdn.rawgit.com/neo4j/neo4j-javascript-driver/1.2/lib/browser/neo4j-web.min.js)

Thanks if you could highlight my path.

Best Regards
Youssef
​
```

**Comment by fancellu** [comment]
It is trying https://github.com/neo4j/neo4j-javascript-driver v1.2

https://neo4j.com/docs/api/javascript-driver/current/

It may be out of date with your neo4j. As you can see, this repo is
quite old

Maybe try
***@***.***/lib/browser/neo4j-web.min.js

here https://github.com/fancellu/neo4j-d3v4/blob/master/index.html#L23

**Comment by yboujraf** [comment]
Dear @fancellu 

Finally, I works. I have replaced the link for the new library (5.4.0), changed the way to call getLinks, getNodes.

Now, I need to understand d3.js library

Best Regards
Youssef
